version: "3.9"

services:

  postgres:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_USER: "todolist_admin"
      POSTGRES_PASSWORD: "todolist_password"
      POSTGRES_DB: "todolist_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_todolist:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  postgres_data_todolist:

