version: "3.8"

services:
  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - todolist_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 3s
      timeout: 10s
      retries: 5

  api:
    image: mashhhhha/todolist:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  bot:
    image: mashhhhha/todolist:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command:
      python manage.py runbot

  collect_static:
    image: mashhhhha/todolist:latest
    env_file: .env
    entrypoint: ''
    volumes:
      - django_static:/opt/static/
    command: python manage.py collectstatic -c --no-input

  frontend:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    volumes:
      - django_static:/usr/share/nginx/html/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
   todolist_pg_data:
   django_static:
